apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-service-nodeport
  name: nginx-service-nodeport
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30080
  type: NodePort